### ISSUE TITLE
SourceLink

### ISSUE THREAD

**Issue by TysonMN** [fslaborg/flips#139]
For an open source project, I don't think SouceLink is the best way to improve the development experience.

The alternative is to include the source in the NuGet package.  The main advantage here is that users do not need an internet connection when they want to see the inspect the source code corresponding to the NuGet package (because they already got it when they obtained the NuGet package).

The main advantage of SourceLink for an open source project is a slightly smaller NuGet package.

Embedding the source in the NuGet package is accomplished with [these two lines](https://github.com/elmish/Elmish.WPF/blob/db20825cc2057b9b464fe56a5752639dd7d9a480/src/Elmish.WPF/Elmish.WPF.fsproj#L9-L10).

I am willing to PR for this.

**Comment by matthewcrews** [comment]
Go for it!
