### ISSUE TITLE
Remove Paket

### ISSUE THREAD

**Issue by TysonMN** [fslaborg/flips#140]
This is a spin off of https://github.com/fslaborg/flips/issues/138#issuecomment-752134887.

Replace Paket with NuGet package dependencies specified in the project files.

I am willing to make this change.

**Comment by matthewcrews** [comment]
Go for it!

**Comment by TysonMN** [comment]
I don't always recommend removing Paket.  [Material Design in XAML](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit) is an example of a project that uses Paket and where I have been able to contribute without any problems from Paket.

Let's try to keep Paket.

On `main`, executing `sh build.sh` successfully compiles the code (and unexpectedly to me also runs the tests, which all pass).  Then in Visual Studio, I have these compile errors.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	FS0078	Unable to find the file 'C:\Code\ThirdParty\flips\Flips\bin\x64\Debug\netstandard2.0\Flips.dll' in any of C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\3.1.0\ref\netcoreapp3.1 C:\Code\ThirdParty\flips\Flips.Examples c:\program files (x86)\microsoft visual studio\2019\enterprise\common7\ide\commonextensions\microsoft\fsharp\	Flips.Examples	C:\Code\ThirdParty\flips\Flips.Examples\FSC	1	Active

Severity	Code	Description	Project	File	Line	Suppression State
Error	FS0078	Unable to find the file 'C:\Code\ThirdParty\flips\Flips\bin\x64\Debug\netstandard2.0\Flips.dll' in any of C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\3.1.0\ref\netcoreapp3.1 C:\Code\ThirdParty\flips\Flips.Tests c:\program files (x86)\microsoft visual studio\2019\enterprise\common7\ide\commonextensions\microsoft\fsharp\	Flips.Tests	C:\Code\ThirdParty\flips\Flips.Tests\FSC	1	Active
```

Why is that?  How can I avoid this?

A temporary workaround is to unload `Flips.Examples` and `Flips.Tests`.  I would prefer not to do that though.

**Comment by TysonMN** [comment]
What I really needed was consistent builds, and I think I have that now that PR #143 is complete.  I don't think Paket is bothering me at the moment.
