### ISSUE TITLE
LinearExpression.Evaluate is incorrect

### ISSUE THREAD

**Issue by matthewcrews** [fslaborg/flips#153]
This line is incorrect in the `LinearExpression.Evaluate` function:

https://github.com/fslaborg/flips/blob/f4df21504d015b13a837fa2f7f902c7ea0411e96/Flips/Types.fs#L236

**Comment by TysonMN** [comment]
This was fixed by PR #151, right?

**Comment by TysonMN** [comment]
Oh, I understand now.  Both `LinearExpression.Reduce` and `LinearExpression.Evaluate` contained the same (syntactic) mistake.  PR #151 fixed the mistake in `LinearExpression.Reduce`.  The make still exists in `LinearExpression.Evaluate`.  I hadn't noticed the problem in `LinearExpression.Reduce`.  I created issue #148 about `LinearExpression.Evaluate`.
