### ISSUE TITLE
Would you be interesting in some background / related links ?

### ISSUE THREAD

**Issue by davidglassborow** [fslaborg/flips#165]
I was wondering if you would be interested in a PR for some background information on discrete optimisation (of which LP and MIP are branches), I've done a couple of excellent Coursera courses on the subject, as well as related software (using local search) that introduces common optimisation problems like knapsack, graph colouring, tsp, etc.

**Comment by matthewcrews** [comment]
Absolutely! Let me know how I can help!

**Comment by davidglassborow** [comment]
Ok I've raised a PR with hopefully some useful background information and learning resources, let me know what you think.
