### ISSUE TITLE
Question - Using objective expression in a constraint

### ISSUE THREAD

**Issue by Iwke** [fslaborg/flips#181]
Hello,

I am rather new to Flips and LP and was doing some reading and trying out stuff in an example.
I was reading Model Building in Mathematical Programming and tried modeling first problem in Flips
The discussion from the book proposes a following model:
![image](https://user-images.githubusercontent.com/18661170/140969678-f8a0e783-c909-4401-b98c-80927583870e.png)

Now in Fsharp I would do something like:
let objectiveExpression = ... // LinearExpression
let constraint = Constraint.create "SomeConstraint" (... - 6.0 * objectiveExpression <== 0)

As soon as I would introduce a constraint such as this into the model, all the decisions would evaluate to 0.

In multiple examples I saw on Flips web site I could not find a similar problem.
Am I on the right track here? Is this even possible to do with Flips?

Thanks,
Ivan.

**Comment by TysonMN** [comment]
Can you share a link to a GitHub repository containing your code?

**Comment by Iwke** [comment]
Hey sorry for a bit of delay, but here's the repo
https://github.com/Iwke/flips-exercises/

Please ignore the entire month/prices matrix, at the moment I am just trying to get optimal values for January.

**Comment by matthewcrews** [comment]
I'll be looking at this later today.

**Comment by matthewcrews** [comment]
Could you provide the page number you are looking at in "Model Building in Mathematical Programming" for me to reference?

I don't see where you need to create a constraint using the Objective Function. What's making you think you need to create something like this...

```
let constraint = Constraint.create "SomeConstraint" (... - 6.0 * objectiveExpression <== 0)
```

**Comment by Iwke** [comment]
Hey kind of difficult to tell the exact page, since I am reading on oreilly.
But it's the first problem from Chapter 12 (problem "Food manufacture 1") and Chapter 13 (formulation and discussion).

Regarding using objective in constraints, take a look at constraints on line 34, 35 and 37.
If I add any of those in the solution all decisions will be 0.
If I remove all of them I get some numbers that add up, but of course do not follow the constraints and therefore are not really useful.

**Comment by matthewcrews** [comment]
Here's a gist of how I would formulate it:
https://gist.github.com/matthewcrews/a5c0c0c2790f4af66f95336d4e3bb0bc

It seems to solve without issue. Result I got:
Profit: 17592.59259
x1: 159.2592593
x2: 40.74074074
x3: 0.0
x4: 250.0
x5: 0.0
y: 450.0
