### ISSUE TITLE
Version 2.4.7 locked to FSharp.Core 5.0.0

### ISSUE THREAD

**Issue by matthewcrews** [fslaborg/flips#183]
- Paket changed the version of FSharp.Core to be = 5.0.0 instead of >= 5.0.0

**Comment by smoothdeveloper** [comment]
Hi @matthewcrews, the simplest, if you want to upgrade it manually and avoid inadvertent updates, is set it explicitly:

https://github.com/fslaborg/flips/blob/08ac5b047e2ad7dcd446ff974bd29b6d9689ce56/paket.dependencies#L12
putting `nuget FSharp.Core = 5` and updating it explicitly when you need.

**Comment by matthewcrews** [comment]
Resolved with version 2.4.8
